### ISSUE TITLE
Cannot fetch documents from application storage. Only supported by assets documents

### ISSUE THREAD

**Issue by Appstute-Prerna** [4Q-s-r-o/thumbnailer#10]
Please add for local application stored documents too.

**Comment by MartinHlavna** [comment]
Hello,
this should be working, but maybe I am not understanding the way you want to fetch documents.

Can you please provide simple project demonstrating the way you want to use this package?

**Comment by MartinHlavna** [comment]
Closing since there is no response. 

See #14 which asks similar question.
