### ISSUE TITLE
How to create thumbnail for image pulled from file_picker package

### ISSUE THREAD

**Issue by nicolasvahidzein** [4Q-s-r-o/thumbnailer#14]
Hello,

Thank you for your package. I was wondering how we can display an image that is of the "File" type retrieved from using the file_picker package.

I see in your example that we can only do asset images, is this correct?

My images are accessed this way: 

```
return Image.file(
	File(_productsPictures[index].path!), 
	fit: BoxFit.cover,
);
```

**Comment by MartinHlavna** [comment]
Hello,
this should not be problem. In example we are using asset images just for simplicity.  Plugin works with data returned from "dataResolver" function. How will you implement is up to you. You just have to return Uint8List. 

Just a quick example I wrote top of my head without testing. Take with a grain of salt. It may need a few adjustements but should show you general direction.
```
Thumbnail(
    dataResolver: () async {
           return File(_productsPictures[index].path!).readAsBytesSync();
    },
    mimeType: 'image/jpg',
    decoration: WidgetDecoration(
        wrapperBgColor: Colors.deepOrange,
        wrapperSize: 110,
    ),
    widgetSize: 100,
),
```

**Comment by nicolasvahidzein** [comment]
Ok thank you very much. Will test and revert back.

**Comment by vidhi002** [comment]
not working on web
