### ISSUE TITLE
Thumbnail for PDF

### ISSUE THREAD

**Issue by mandanshubham** [4Q-s-r-o/thumbnailer#2]
Hi there!
I want to ask that, does this plugin able to show a thumbnail when a pdf file is loaded from the device storage?

If yes, it would be really helpful and appreciable if you share the code for particular.

BTW Nice plugin!!

**Comment by MartinHlavna** [comment]
It shouldn't matter from where the data is loaded. It could be loaded from assets, device storage, network... you just have to provide  ```Uint8List``` with data from ```dataResolver``` function.

```
Thumbnail(
    dataResolver: () async {
        //LOAD YOUR DATA HERE
    },
    mimeType: 'image/png',
    widgetSize: 100,
),
```
