### ISSUE TITLE
Can I add thumbnail in zip file?

### ISSUE THREAD

**Issue by tomriddle7** [4Q-s-r-o/thumbnailer#4]
I want to make comic viewer and add thumbnail in zip file.

I found this package but it don't look like support thumbnail for zip file.

Can  you add zip support?

**Comment by MartinHlavna** [comment]
Hi,

sounds like you need to create thumbnail from zip contents. This is somewhat not standard enough to be included in plugin itself. For this I suggest to add your own generation strategy by calling 

```Thumnailer.addCustomGenerationStrategies``` (e.g. before calling flutter right before ```runApp``)
