### ISSUE TITLE
Generating thumbnail for pdf

### ISSUE THREAD

**Issue by LucaJeevanjee** [4Q-s-r-o/thumbnailer#6]
All my fields have values so not sure what's happening here

![image](https://user-images.githubusercontent.com/30826343/154502803-efe279b9-675b-409c-903a-a949566a56cb.png)

![image](https://user-images.githubusercontent.com/30826343/154502605-d4c4dd73-d24f-41a0-9b98-a846b7403034.png)

**Comment by MartinHlavna** [comment]
Hello,

are you sure this is caused by ```thumbnailer```? 

```PlatformException``` is thrown by flutter when it encounters Exception in platform specific code. This package is pure dart thought.
